apiVersion: v1
kind: Service
metadata:
  name: database-service
  labels:
    app: database
spec:
  ports:
  - protocol: TCP
    port: 1111
    targetPort: 5432
    name: database
  type: LoadBalancer
  selector:
    app: database