apiVersion: v1
kind: Service
metadata:
  name: database-app
  namespace: database-namespace
  labels:
    app: database-app
spec:
  selector:
    app: database-app
  ports:
  - protocol: TCP
    port: 1111
    targetPort: 5432
    name: database-port
  type: LoadBalancer