apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: 
  namespace: database-namespace
  labels:
    app: database-stateful
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-stateful
  serviceName: database-service
  template:
    metadata:
      labels:
        app: database-stateful
    spec:
      containers:
      - name: database-container
        image: postgres:16.3
        volumeMounts:
          - name: database-disk
            mountPath: /var/lib/postgresql/data
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: database-disk
      spec:
        accessModes: ["ReadWrteOnce"]
        resources:
          requests:
            storage: 5Gi
